import { PortfolioData } from './types';

export const defaultPortfolioData: PortfolioData = {
  profile: {
    name: 'Gabriel Rios',
    initials: 'GR',
    logoUrl: '',
    profilePhotoUrl: '',
    role: 'Analista Funcional & Visual Creator Canva IA',
    email: 'gaboriosadrian@gmail.com',
    phone: '+54 9 2617486990',
    whatsappMessage: 'Hola, me interesa conocer sobre el desarrollo de contenido para iniciar un proyecto.',
    instagram: '@gabrielriosok',
    tiktok: '',
    linkedin: 'gabriel rios',
  },
  hero: {
    eyebrow: 'Analista Funcional & Visual Creator',
    title: 'Ayudo a marcas a destacar y',
    gradientTitle: 'atraer clientes.',
    copy: 'Ayudo a marcas personales, coaches y negocios a transformar ideas en Reels, fotos, guiones y calendarios de contenido claros, auténticos y orientados a generar confianza. Combinando diseño, música y fotografía transformo el cambio digital.',
    trustTags: [
      '⚡ Respuesta en 24h',
      '📅 Calendario mensual',
      '🎬 Reels + fotos + copy',
      '🔁 Contenido adaptable',
    ],
  },
  metrics: [
    { id: 'm1', value: '24h', label: 'respuesta inicial' },
    { id: 'm2', value: '4', label: 'pilares de contenido' },
    { id: 'm3', value: '100%', label: 'adaptable a redes' },
    { id: 'm4', value: '1', label: 'flujo simple y claro' },
  ],
  services: [
    {
      id: 's1',
      icon: 'Compass',
      title: 'Estrategia de contenido',
      description: 'Definición de pilares, objetivos, tono de voz, ideas clave y calendario editorial mensual.',
      ctaText: 'Solicitar estrategia',
    },
    {
      id: 's2',
      icon: 'Video',
      title: 'Reels y videos cortos',
      description: 'Guiones, grabación, edición dinámica, subtítulos, hooks y llamadas a la acción.',
      ctaText: 'Crear Reels',
    },
    {
      id: 's3',
      icon: 'Camera',
      title: 'Fotografía de marca',
      description: 'Sesiones visuales para mostrar tu estilo, tu proceso, tus servicios y tu personalidad.',
      ctaText: 'Renovar imagen',
    },
    {
      id: 's4',
      icon: 'PenTool',
      title: 'Copywriting y storytelling',
      description: 'Textos que explican lo que haces de forma clara, humana y orientada a convertir.',
      ctaText: 'Mejorar textos',
    },
    {
      id: 's5',
      icon: 'Calendar',
      title: 'Gestión de redes',
      description: 'Programación, optimización de perfiles, publicaciones, historias y seguimiento básico.',
      ctaText: 'Gestionar redes',
    },
    {
      id: 's6',
      icon: 'Sparkles',
      title: 'Marca personal',
      description: 'Posicionamiento visual y narrativo para que tu audiencia entienda quién eres y por qué confiar.',
      ctaText: 'Potenciar marca',
    },
  ],
  projects: [
    {
      id: 'p1',
      title: 'Serie: “Errores que te hacen perder clientes”',
      description: 'Reels con hook, estructura clara y CTA para generar comentarios y mensajes privados.',
      categories: ['reels', 'copy'],
      badge: 'Reel educativo',
      iconType: 'play',
      colorType: 'reels',
      tags: ['Reels', 'Guion', 'CTA'],
      imageUrl: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=800&q=85',
      videoUrl: '', // Agrega aquí el enlace de YouTube o archivo .mp4 si quieres un reproductor de video interactivo
    },
    {
      id: 'p2',
      title: 'Biblioteca de fotos para marca personal',
      description: 'Imágenes para mostrar proceso, lifestyle, servicios, detrás de cámaras y autoridad.',
      categories: ['foto', 'marca'],
      badge: 'Sesión visual',
      iconType: 'camera',
      colorType: 'foto',
      tags: ['Fotografía', 'Marca'],
      imageUrl: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=800&q=85',
    },
    {
      id: 'p3',
      title: 'Mapa de identidad y tono de voz',
      description: 'Definición de mensaje principal, promesa, valores visuales y frases clave de la marca.',
      categories: ['marca', 'copy'],
      badge: 'Posicionamiento',
      iconType: 'sparkles',
      colorType: 'marca',
      tags: ['Marca', 'Estrategia'],
      imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=85',
    },
    {
      id: 'p4',
      title: 'Biografía optimizada para Instagram',
      description: 'Texto claro para explicar qué haces, para quién trabajas y qué acción debe tomar tu audiencia.',
      categories: ['copy', 'marca'],
      badge: 'Copywriting',
      iconType: 'pen',
      colorType: 'copy',
      tags: ['Bio', 'Copy'],
      imageUrl: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&w=800&q=85',
    },
    {
      id: 'p5',
      title: 'Historias de clientes y casos de uso',
      description: 'Formatos breves para demostrar resultados, experiencia y confianza sin sonar forzado.',
      categories: ['reels', 'marca'],
      badge: 'Reel de autoridad',
      iconType: 'play',
      colorType: 'reels',
      tags: ['Reels', 'Prueba social'],
      imageUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=85',
    },
    {
      id: 'p6',
      title: 'Carrusel educativo para guardar',
      description: 'Contenido paso a paso diseñado para educar, aportar valor y atraer clientes potenciales.',
      categories: ['foto', 'copy'],
      badge: 'Carrusel',
      iconType: 'grid',
      colorType: 'foto',
      tags: ['Diseño', 'Copy'],
      imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=85',
    },
  ],
  steps: [
    {
      id: 'st1',
      number: 1,
      title: 'Brief y objetivos',
      description: 'Revisamos tu marca, servicios, audiencia, estilo visual y metas principales de contenido.',
    },
    {
      id: 'st2',
      number: 2,
      title: 'Estrategia',
      description: 'Definimos pilares, formatos, calendario, tono de voz y mensajes clave para cada etapa.',
    },
    {
      id: 'st3',
      number: 3,
      title: 'Producción',
      description: 'Creo guiones, grabo o diseño piezas, edito videos y preparo textos listos para publicar.',
    },
    {
      id: 'st4',
      number: 4,
      title: 'Optimización',
      description: 'Ajustamos según rendimiento, comentarios y oportunidades para mejorar la conexión con tu audiencia.',
    },
  ],
  plans: [
    {
      id: 'pl1',
      title: 'Arranque',
      price: '290€',
      period: '/ mes',
      description: 'Ideal si quieres ordenar tu contenido y empezar a publicar con más intención.',
      features: [
        '8 piezas mensuales',
        'Calendario editorial básico',
        'Copy para publicaciones',
        'Optimización de bio y perfil',
      ],
      featured: false,
      buttonText: 'Elegir Arranque',
    },
    {
      id: 'pl2',
      title: 'Crecimiento',
      price: '590€',
      period: '/ mes',
      description: 'Para marcas que quieren presencia constante en Reels, historias y publicaciones.',
      features: [
        '16 piezas mensuales',
        '4 Reels editados',
        'Guiones y copywriting',
        'Calendario + sugerencias de historias',
      ],
      featured: true,
      buttonText: 'Elegir Crecimiento',
    },
    {
      id: 'pl3',
      title: 'Premium',
      price: '990€',
      period: '/ mes',
      description: 'Soporte completo para construir autoridad, confianza y un sistema de contenido mensual.',
      features: [
        '24 piezas mensuales',
        '8 Reels editados',
        'Sesión visual de marca',
        'Estrategia y revisión mensual',
      ],
      featured: false,
      buttonText: 'Elegir Premium',
    },
  ],
};
